// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_auth_callback from "./routes/api/auth/callback.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_status from "./routes/api/auth/status.ts";
import * as $api_drip_count from "./routes/api/drip-count.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_og_image from "./routes/api/og-image.ts";
import * as $api_pins_index from "./routes/api/pins/index.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MastodonLogin from "./islands/MastodonLogin.tsx";
import * as $SweatCounter from "./islands/SweatCounter.tsx";
import * as $WorldMap from "./islands/WorldMap.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/auth/callback.ts": $api_auth_callback,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/status.ts": $api_auth_status,
    "./routes/api/drip-count.ts": $api_drip_count,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/og-image.ts": $api_og_image,
    "./routes/api/pins/index.ts": $api_pins_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/MastodonLogin.tsx": $MastodonLogin,
    "./islands/SweatCounter.tsx": $SweatCounter,
    "./islands/WorldMap.tsx": $WorldMap,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
